### ISSUE TITLE
Seems the extension is not registering correctly

### ISSUE THREAD

**Issue by lmajano** [Ortus-Solutions/vscode-testbox#2]
Several people have reported there is always a `reload` button on the extension in the extensions panel and none of the snippets actually work.  

Can you verify this, I can verify the behavior.

**Comment by ilich** [comment]
There was a configuration issue at package.json. This plugin has only snippets at the moment and does not require `activationEvents` settings. I've also updated plugin version to 0.1.1. Please publish it to the marketplace.
